import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Mangal Dhaba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-rows-2 items-center my-20'>
        <div>
          <h1>Lorem ipsum dolor sit amet.</h1>
        </div>
        <div className='flex flex-col text-[40px] items-center text-center font-vollkron'>
          <button onClick={() => router.push('/gravity-grill')}>Explore More!</button>
          <button>Download our App</button>
        </div>
      </div>
    </>
  )
}
