# -*- coding: utf-8 -*-
"""GravityGrillBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDBQ2MG2gabEK6r8MXozqGopqabH08lE
"""

!pip install gradio

import gradio as gr

def get_info(name, day, info, price_range=None):
    if day == "Monday":
        time = "10:00am to 10:00pm"
        dish = "Spaghetti and Meatballs"
        menu = [
            {"name": "Caesar Salad", "price": 9.99},
            {"name": "Margherita Pizza", "price": 12.99},
            {"name": "Fettuccine Alfredo", "price": 15.99},
        ]
    elif day == "Tuesday":
        time = "10:00am to 10:00pm"
        dish = "Taco Salad"
        menu = [
            {"name": "Chips and Guacamole", "price": 6.99},
            {"name": "Carnitas Tacos", "price": 9.99},
            {"name": "Churros", "price": 5.99},
        ]
    elif day == "Wednesday":
        time = "10:00am to 10:00pm"
        dish = "Beef Stir Fry"
        menu = [
            {"name": "Spring Rolls", "price": 7.99},
            {"name": "Pad Thai", "price": 14.99},
            {"name": "Mango Sticky Rice", "price": 8.99},
        ]
    elif day == "Thursday":
        time = "10:00am to 10:00pm"
        dish = "Fish and Chips"
        menu = [
            {"name": "Clam Chowder", "price": 6.99},
            {"name": "Lobster Roll", "price": 18.99},
            {"name": "Boston Cream Pie", "price": 7.99},
        ]
    elif day == "Friday":
        time = "10:00am to 11:00pm"
        dish = "Grilled Cheese and Tomato Soup"
        menu = [
            {"name": "Fried Pickles", "price": 5.99},
            {"name": "Lobster Mac and Cheese", "price": 21.99},
            {"name": "Chocolate Chip Cookie", "price": 4.99},
        ]
    elif day == "Saturday":
        time = "10:00am to 11:00pm"
        dish = "BBQ Ribs"
        menu = [
            {"name": "Cornbread", "price": 4.99},
            {"name": "Pulled Pork Sandwich", "price": 12.99},
            {"name": "Sweet Potato Pie", "price": 6.99},
        ]
    elif day == "Sunday":
        time = "10:00am to 11:00pm"
        dish = "Roast Beef Dinner"
        menu = [
            {"name": "Butternut Squash Soup", "price": 6.99},
            {"name": "Beef Wellington", "price": 24.99},
            {"name": "Apple Pie", "price": 8.99},
        ]
    else:
        time = "N/A"
        dish = "N/A"
        menu = []

    if price_range:
        min_price, max_price = price_range.split("-")
        filtered_menu = [item for item in menu if item["price"] >= float(min_price) and item["price"] <= float(max_price)]
        menu = filtered_menu
    
    if info.lower() == "timings":
        output = f"Hello {name}, the restaurant timings for {day} are {time}"
    elif info.lower() == "menu":
        if price_range:
            output = f"Hello {name}, the restaurant's menu for {day} between {min_price} and {max_price} dollars is:\n"
        else:
            output = f"Hello {name}, the restaurant's menu for {day} is:\n"
        for item in menu:
            output += f"{item['name']} - ${item['price']}\n"
    elif info.lower() == "dish":
        output = f"Hello {name}, the dish of the day for {day} is {dish}"
    else:
        output = "Please enter either 'timings', 'menu', or 'dish' to see the restaurant's timings, menu, or dish of the day."
    
    return output

name_input = gr.inputs.Textbox(label="What is your name?")
day_input = gr.inputs.Dropdown(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], label="What day of the week is it?")
info_input = gr.inputs.Radio(["Timings", "Menu", "Dish"], label="Do you want to see the timings, menu or dish of the day?")
price_input = gr.inputs.Textbox(label="Enter a price range to filter the menu (e.g. 10-15)")

outputs = [gr.outputs.Textbox(label="Output")]

interface = gr.Interface(fn=get_info, inputs=[name_input, day_input, info_input, price_input], outputs=outputs, title="Chat with Elon", description="Elon is an amazing friend, it will help you get information about timings, menu, dish of the day and help you sort the dishes as per your budget.")
interface.launch()